### ISSUE TITLE
Create data fails

### ISSUE THREAD

**Issue by miseiler** [YStrauch/CI-SpliceAI__Train#1]
When attempting to create_data.py, progress gets to 2% and I get a failure:
`Worker 1 of 1 starting
##------------------------------------------------------------------------------ (2%)Traceback (most recent call last):
  File "create_data.py", line 130, in <module>
    raise e
  File "create_data.py", line 127, in <module>
    process_gene(gene, out_x, out_y)
  File "create_data.py", line 87, in process_gene
    assert len(x) == len(y)
AssertionError`

**Comment by YStrauch** [comment]
First of all, apologies for the late reply, I don't have the time to actively maintain this project.

Second, I was able to setup and create the data project following the readme. I can only guess what might be going wrong on your end.

Try deleting everything in `data/raw`, which is third party data that will be re-downloaded. Maybe you have cancelled the download prematurely?

Or, it might be a dependency issue which is really hard to debug unfortunately. I documented which versions I use and it's really hard to help you. I hope it was a cancelled download.
